theme: jekyll-theme-cayman
ul, li {
	margin: 0;
	padding: 0;
	list-style: none;
}
.slideshow {
	position: relative;
	height: 160px;
	width: 210px;
	float: left;
	margin: 0 10px;
	border: 3px solid #ddd;
}
.slideshow li {
	position: absolute;
}
.slideshow a img{
	display: block;
	padding: 0;
	margin: 0 auto;
	border: none;
}
.slideshow li a{
	display: block;
}
.slideshowController {
	position: absolute;
	right: 0;
	bottom: 0;
}
.slideshowController a {
	background: transparent url(images/arrows.png) no-repeat left top;
	display: block;
	width: 30px;
	height: 30px;
	position: absolute;
	right: 60px;
	bottom: 0;
	z-index: 9999;
	outline: none;
}
.slideshowController .next{
	background-position: -30px 0;
	right: 0;
}
.slideshowController .play{
	background-position: -60px 0;
	right: 30px;
}
.slideshowController .pause{
	background-position: -90px 0;
}

$(function(){

	var _fadeSpeed = 600;

	$('.slideshow').each(function(){

		var $this = $(this), 
			$ul = $this.find('ul'), 
			$li = $ul.find('li'), 
			$controller = $('<div class="slideshowController"><a href="#"></a><a href="#" class="play"></a><a href="#" class="next"></a></div>').css('opacity', 0), 
			_len = $li.length, 
			_index = 0, timer, _speed = 2000;

		$li.eq(_index).css('z-index', 2).siblings().css('opacity', 0);

		$this.append($controller).hover(function(){
			$controller.stop().animate({
				opacity: 1
			});
		}, function(){
			$controller.stop().animate({
				opacity: 0
			});
		});

		$controller.delegate('a', 'click', function(){

			var $a = $(this), 
				_className = $a.attr('class');

			if(('play pause').indexOf(_className) > -1){

				$a.toggleClass('pause').hasClass('pause') ? timer = setTimeout(autoClickNext, _fadeSpeed + _speed) : clearTimeout(timer);
				return false;
			}
 

			clearTimeout(timer);

			$a.siblings('.pause').removeClass('pause');

			_index = ('next' == _className ? _index + 1 : _index - 1 + _len) % _len;

			show();
 
			return false;
		});

		function autoClickNext() {
			_index = (_index + 1) % _len;
			show();
			timer = setTimeout(autoClickNext, _fadeSpeed + _speed);
		}
 
		function show() {
			$li.eq(_index).animate({
				opacity: 1, 
				zIndex: 2
			}, _fadeSpeed).siblings(':visible').animate({
				opacity: 0, 
				zIndex: 1
			}, _fadeSpeed);
		}
	});
});
